### PR TITLE
Add results for scoophealth/oscar

### PR DESCRIPTION
**Pull request by algomaster99**

### CODE REVIEW

**Comment by monperrus** [comment]
It's really nice, it's exactly what's needed to showcase Sorald!

The last minor thing is to add a link to the corresponding diff file in each README section.

Thanks!

**Comment by algomaster99** [comment]
Sure, I will do that.

I also wanted to point that there were many errors encountered while sorald was repairing (you may count the number of "Errors were thrown in README.md"). I think we should also open issues corresponding to them. It may be hard to debug it because running sorald on the entire project takes a huge amount of time!

**Comment by monperrus** [comment]
> Sure, I will do that.

thanks.

>  I think we should also open issues corresponding to them

yes, excellent idea. some bugs may be related to the issues opened by @khaes-kth recently.

**Comment by algomaster99** [comment]
> yes, excellent idea.

I will try to find them and open issues for them if they are different from what @khaes-kth found. But for now, I am focussing more on things left in gumtree-spoon.

**Comment by algomaster99** [comment]
@monperrus ping for reviews.

**Comment by monperrus** [comment]
Thanks a lot @algomaster99

**Pull request merged**
